### ISSUE TITLE
wagtail-schema.org requires a licence

### ISSUE THREAD

**Issue by evildmp** [takeflight/wagtail-schema.org#2]
We'd like to make this available as an addon on the Divio Cloud, but we can't unless it has a licence (and indeed, many companies won't be able to use it either).

Will you consider releasing it under a suitable licence?

Thanks.

**Comment by timheap** [comment]
Oh sorry, I must have forgotten that step. I usually use the BSD 2-clause license. I'll add that and get this updated right away.

**Comment by timheap** [comment]
Added in https://github.com/takeflight/wagtail-schema.org/commit/82689ae096dd402039bbbfa07626e2c2fa90344e
