### ISSUE TITLE
Problem locating package on pypi

### ISSUE THREAD

**Issue by marteinn** [takeflight/wagtail-schema.org#5]
When running `pip install wagtailschemaorg` I got the following error message.

```
Could not find a version that satisfies the requirement wagtailschemaorg (from versions: )
No matching distribution found for wagtailschemaorg
```

... while`pip install wagtail-schema.org` works fine

The docs states `wagtailschemaorg`, should it be changed to `wagtail-schema.org`?

Debug info:

```
$ pip -V
$ pip 9.0.1 from /usr/local/lib/python2.7/site-packages (python 2.7)

$ python -V
$ Python 2.7.13

```

Thanks for the library! 👍

**Comment by timheap** [comment]
@marteinn You are right, the README was incorrect. I've fixed it. Thanks for pointing it out!

**Comment by marteinn** [comment]
@timheap Awesome! Thanks for the quick fix!
